//
// Created by Lorenzo Dinardo on 26/09/22.
//

#ifndef LABORATORIOPROG_LORENZODINARDO_FILEMANAGER_H
#define LABORATORIOPROG_LORENZODINARDO_FILEMANAGER_H
#include "Observer.cpp"


#endif //LABORATORIOPROG_LORENZODINARDO_FILEMANAGER_H
